### ISSUE TITLE
SteamVR

### ISSUE THREAD

**Issue by FoofPoof** [MayouKurayami/KK_SetParentVR#1]
Does any of this work in SteamVR? Can it work in SteamVR?

**Comment by MayouKurayami** [comment]
This is a plugin for Koikatsu, whose VR mode runs in SteamVR.

**Comment by FoofPoof** [comment]
I should have been more specific. Does this work with Koikatsu Party? Can it work?

**Comment by MayouKurayami** [comment]
First bullet point here:
https://github.com/MayouKurayami/KK_SetParentVR#notes-and-limitations

I don't have Koikatsu Party VR so I can't test it.
It may work, so feel free to try.

**Comment by FoofPoof** [comment]
None of your KK mods work but I feel like it should since the only thing that changes is the language part. Unless I am doing something wrong. It works with HF Patch 3.3 right? I could provide screenshots to where I installed them if you want.

**Comment by MayouKurayami** [comment]
Koikatsu Party has major code changes from the JP version, which is why it breaks compatibility with many other plugins.
My VR plugins work fine with HF Patch on the JP version. 

Providing ***output_log.txt*** located under the game's root directory will be more helpful.

**Comment by FoofPoof** [comment]
[output_log.txt](https://github.com/MayouKurayami/KK_SetParentVR/files/5034551/output_log.txt)

**Comment by FoofPoof** [comment]
I could provide you with more things to make your plugins work with Koikatsu Party if you aren't busy.

**Comment by MayouKurayami** [comment]
It could be that you're using Oculus Quest, which isn't officially supported by Koikatsu VR and really isn't designed to play well with VR titles on the PC.

From the output_log:
> Your headset is of type 'oculusquest' which VRTK doesn't know about yet.

**Comment by FoofPoof** [comment]
Well the thing is I’ve downloaded Koikatsu better repack and installed your plugins and they seem to work with my Quest.

**Comment by MayouKurayami** [comment]
Not sure why they don't work on Koikatsu Party VR then.
From the output_log the plugins seem to have loaded and I didn't see any obvious errors.

Like I said I have neither Koikatsu Party VR or the Oculus Quest to test, so I'm afraid there is not much I can do from here.
