### ISSUE TITLE
Is there a plan to support kks in the future?

### ISSUE THREAD

**Issue by WelchYang** [MayouKurayami/KK_SetParentVR#6]
This plugin is awesome, I really like it.
Is there a plan to support kks in the future? The vr operation on kks is better adapted as well as the picture quality is better. And kks has a much better studio vr

**Comment by MayouKurayami** [comment]
Unfortunately I haven't really had the time or energy to get into KKS at all (or even KK for that matter).
Though from what I've heard, some Japanese modders have ported this to KKS and uploaded it on http://uppervolta-3d.net/illu/upload.php.
